# Generated by Django 6.0.4 on 2026-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Thành tích', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Nội dung Markdown cho trang thành tích')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang thành tích',
                'verbose_name_plural': 'Trang thành tích',
            },
        ),
    ]
