# Generated by Django 6.0.4 on 2026-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Về chúng mình', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Nội dung Markdown cho trang giới thiệu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang giới thiệu',
                'verbose_name_plural': 'Trang giới thiệu',
            },
        ),
        migrations.CreateModel(
            name='MemberPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Thành viên', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Nội dung Markdown cho trang thành viên')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang thành viên',
                'verbose_name_plural': 'Trang thành viên',
            },
        ),
    ]
